datos = [
    {'nombre': 'Carlos', 'edad': 30, 'soltero': False, 'hobbies': ['fotografía', 'ciclismo', 'ajedrez'], 'email': 'carlos0@mail.org', 'puntos': 979},
    {'nombre': 'Pedro', 'edad': 52, 'soltero': False, 'hobbies': ['pintura', 'ciclismo', 'ajedrez'], 'email': 'pedro1@mail.org', 'puntos': 500},
    {'nombre': 'Luis', 'edad': 27, 'soltero': True, 'hobbies': [], 'email': 'luis2@correo.com', 'puntos': 532},
    {'nombre': 'Carlos', 'edad': 47, 'soltero': False, 'hobbies': ['natación'], 'email': 'carlos3@correo.com', 'puntos': 630},
    {'nombre': 'Ana', 'edad': 60, 'soltero': False, 'hobbies': ['fotografía'], 'email': 'ana4@mail.org', 'puntos': 472},
    {'nombre': 'Tomás', 'edad': 40, 'soltero': True, 'hobbies': ['lectura', 'ciclismo'], 'email': None, 'puntos': 967},
    {'nombre': 'Ana', 'edad': 54, 'soltero': True, 'hobbies': [], 'email': 'ana6@mail.org', 'puntos': 989},
    {'nombre': 'Sofía', 'edad': 54, 'soltero': True, 'hobbies': ['senderismo', 'fotografía', 'ciclismo'], 'email': 'sofía7@example.com', 'puntos': 618},
    {'nombre': 'Diego', 'edad': 55, 'soltero': False, 'hobbies': ['videojuegos'], 'email': 'diego8@example.com', 'puntos': 946},
    {'nombre': 'Lucía', 'edad': 57, 'soltero': True, 'hobbies': [], 'email': None, 'puntos': 867},
    {'nombre': 'Ana', 'edad': 29, 'soltero': True, 'hobbies': [], 'email': 'ana10@mail.org', 'puntos': 361},
    {'nombre': 'Tomás', 'edad': 41, 'soltero': True, 'hobbies': ['ciclismo'], 'email': 'tomás11@mail.org', 'puntos': 383},
    {'nombre': 'Pedro', 'edad': 21, 'soltero': True, 'hobbies': ['ajedrez', 'videojuegos', 'ciclismo'], 'email': 'pedro12@correo.com', 'puntos': 908},
    {'nombre': 'Luis', 'edad': 60, 'soltero': False, 'hobbies': ['videojuegos'], 'email': 'luis13@example.com', 'puntos': 770},
    {'nombre': 'Carlos', 'edad': 23, 'soltero': True, 'hobbies': [], 'email': 'carlos14@correo.com', 'puntos': 443},
    {'nombre': 'Lucía', 'edad': 30, 'soltero': True, 'hobbies': ['senderismo', 'pintura'], 'email': 'lucía15@correo.com', 'puntos': 602},
    {'nombre': 'Ana', 'edad': 48, 'soltero': True, 'hobbies': ['ajedrez'], 'email': None, 'puntos': 993},
    {'nombre': 'Ana', 'edad': 49, 'soltero': False, 'hobbies': ['lectura', 'senderismo', 'videojuegos'], 'email': 'ana17@example.com', 'puntos': 476},
    {'nombre': 'Sofía', 'edad': 58, 'soltero': False, 'hobbies': ['senderismo', 'fotografía'], 'email': 'sofía18@example.com', 'puntos': 91},
    {'nombre': 'Sofía', 'edad': 39, 'soltero': False, 'hobbies': [], 'email': 'sofía19@example.com', 'puntos': 301},
    {'nombre': 'Tomás', 'edad': 32, 'soltero': True, 'hobbies': [], 'email': 'tomás20@correo.com', 'puntos': 371},
    {'nombre': 'Ana', 'edad': 57, 'soltero': False, 'hobbies': ['videojuegos', 'senderismo'], 'email': 'ana21@correo.com', 'puntos': 430},
    {'nombre': 'Luis', 'edad': 41, 'soltero': True, 'hobbies': ['senderismo'], 'email': None, 'puntos': 268},
    {'nombre': 'Tomás', 'edad': 63, 'soltero': False, 'hobbies': [], 'email': 'tomás23@correo.com', 'puntos': 968},
    {'nombre': 'Pedro', 'edad': 19, 'soltero': True, 'hobbies': ['videojuegos', 'fotografía', 'ajedrez'], 'email': 'pedro24@correo.com', 'puntos': 392},
    {'nombre': 'Tomás', 'edad': 22, 'soltero': True, 'hobbies': ['fotografía', 'lectura'], 'email': 'tomás25@example.com', 'puntos': 106},
    {'nombre': 'Lucía', 'edad': 26, 'soltero': False, 'hobbies': ['ciclismo'], 'email': None, 'puntos': 76},
    {'nombre': 'Marta', 'edad': 47, 'soltero': True, 'hobbies': ['senderismo'], 'email': 'marta27@correo.com', 'puntos': 166},
    {'nombre': 'Diego', 'edad': 18, 'soltero': False, 'hobbies': ['lectura', 'fotografía', 'ciclismo'], 'email': 'diego28@example.com', 'puntos': 357},
    {'nombre': 'Luis', 'edad': 29, 'soltero': False, 'hobbies': ['natación'], 'email': None, 'puntos': 595},
    {'nombre': 'Sofía', 'edad': 26, 'soltero': True, 'hobbies': ['lectura', 'pintura'], 'email': 'sofía30@example.com', 'puntos': 821},
    {'nombre': 'Luis', 'edad': 25, 'soltero': False, 'hobbies': ['lectura', 'ajedrez'], 'email': 'luis31@mail.org', 'puntos': 218},
    {'nombre': 'Pedro', 'edad': 26, 'soltero': False, 'hobbies': [], 'email': 'pedro32@mail.org', 'puntos': 127},
    {'nombre': 'Tomás', 'edad': 31, 'soltero': False, 'hobbies': [], 'email': 'tomás33@correo.com', 'puntos': 975},
    {'nombre': 'Valentina', 'edad': 20, 'soltero': False, 'hobbies': ['videojuegos', 'ciclismo', 'lectura'], 'email': 'valentina34@mail.org', 'puntos': 446},
    {'nombre': 'Valentina', 'edad': 45, 'soltero': False, 'hobbies': ['natación', 'ciclismo'], 'email': 'valentina35@mail.org', 'puntos': 298},
    {'nombre': 'Lucía', 'edad': 53, 'soltero': False, 'hobbies': ['pintura'], 'email': 'lucía36@example.com', 'puntos': 830},
    {'nombre': 'Luis', 'edad': 19, 'soltero': True, 'hobbies': [], 'email': 'luis37@example.com', 'puntos': 251},
    {'nombre': 'Ana', 'edad': 24, 'soltero': False, 'hobbies': ['senderismo', 'ajedrez'], 'email': 'ana38@example.com', 'puntos': 5},
    {'nombre': 'Marta', 'edad': 58, 'soltero': True, 'hobbies': ['senderismo'], 'email': 'marta39@correo.com', 'puntos': 998},
    {'nombre': 'Valentina', 'edad': 37, 'soltero': True, 'hobbies': ['ajedrez', 'lectura'], 'email': None, 'puntos': 848},
    {'nombre': 'Ana', 'edad': 29, 'soltero': True, 'hobbies': [], 'email': 'ana41@example.com', 'puntos': 919},
    {'nombre': 'Lucía', 'edad': 56, 'soltero': True, 'hobbies': ['natación', 'ajedrez', 'pintura'], 'email': 'lucía42@correo.com', 'puntos': 56},
    {'nombre': 'Valentina', 'edad': 40, 'soltero': True, 'hobbies': ['ciclismo', 'fotografía', 'ajedrez'], 'email': 'valentina43@mail.org', 'puntos': 728},
    {'nombre': 'Marta', 'edad': 60, 'soltero': False, 'hobbies': [], 'email': 'marta44@mail.org', 'puntos': 680},
    {'nombre': 'Diego', 'edad': 51, 'soltero': False, 'hobbies': [], 'email': 'diego45@example.com', 'puntos': 162},
    {'nombre': 'Pedro', 'edad': 39, 'soltero': True, 'hobbies': ['videojuegos'], 'email': 'pedro46@example.com', 'puntos': 969},
    {'nombre': 'Pedro', 'edad': 24, 'soltero': True, 'hobbies': ['fotografía', 'natación'], 'email': 'pedro47@example.com', 'puntos': 280},
    {'nombre': 'Lucía', 'edad': 27, 'soltero': False, 'hobbies': ['videojuegos', 'ciclismo'], 'email': 'lucía48@mail.org', 'puntos': 69},
    {'nombre': 'Lucía', 'edad': 23, 'soltero': True, 'hobbies': ['senderismo', 'lectura'], 'email': 'lucía49@mail.org', 'puntos': 269},
    {'nombre': 'Lucía', 'edad': 24, 'soltero': False, 'hobbies': [], 'email': 'lucía50@example.com', 'puntos': 790},
    {'nombre': 'Sofía', 'edad': 38, 'soltero': True, 'hobbies': ['lectura'], 'email': 'sofía51@example.com', 'puntos': 227},
    {'nombre': 'Lucía', 'edad': 60, 'soltero': False, 'hobbies': ['senderismo'], 'email': 'lucía52@example.com', 'puntos': 237},
    {'nombre': 'Lucía', 'edad': 20, 'soltero': True, 'hobbies': ['ajedrez', 'videojuegos'], 'email': 'lucía53@correo.com', 'puntos': 881},
    {'nombre': 'Lucía', 'edad': 35, 'soltero': False, 'hobbies': ['ciclismo'], 'email': 'lucía54@correo.com', 'puntos': 459},
    {'nombre': 'Sofía', 'edad': 65, 'soltero': True, 'hobbies': ['ciclismo', 'videojuegos'], 'email': None, 'puntos': 917},
    {'nombre': 'Tomás', 'edad': 22, 'soltero': False, 'hobbies': ['pintura', 'lectura', 'videojuegos'], 'email': 'tomás56@mail.org', 'puntos': 959},
    {'nombre': 'Valentina', 'edad': 51, 'soltero': False, 'hobbies': ['lectura', 'pintura'], 'email': None, 'puntos': 815},
    {'nombre': 'Lucía', 'edad': 44, 'soltero': True, 'hobbies': ['senderismo', 'ciclismo', 'fotografía'], 'email': 'lucía58@mail.org', 'puntos': 653},
    {'nombre': 'Ana', 'edad': 53, 'soltero': True, 'hobbies': ['pintura', 'natación', 'senderismo'], 'email': 'ana59@example.com', 'puntos': 452},
    {'nombre': 'Tomás', 'edad': 58, 'soltero': False, 'hobbies': ['lectura', 'ciclismo', 'pintura'], 'email': 'tomás60@example.com', 'puntos': 566},
    {'nombre': 'Sofía', 'edad': 59, 'soltero': False, 'hobbies': [], 'email': None, 'puntos': 755},
    {'nombre': 'Tomás', 'edad': 34, 'soltero': False, 'hobbies': [], 'email': None, 'puntos': 326},
    {'nombre': 'Tomás', 'edad': 32, 'soltero': False, 'hobbies': ['senderismo', 'lectura'], 'email': None, 'puntos': 60},
    {'nombre': 'Sofía', 'edad': 42, 'soltero': False, 'hobbies': ['videojuegos', 'ajedrez'], 'email': 'sofía64@mail.org', 'puntos': 773},
    {'nombre': 'Marta', 'edad': 43, 'soltero': False, 'hobbies': ['lectura', 'videojuegos'], 'email': None, 'puntos': 229},
    {'nombre': 'Pedro', 'edad': 61, 'soltero': True, 'hobbies': ['lectura', 'senderismo'], 'email': 'pedro66@example.com', 'puntos': 546},
    {'nombre': 'Lucía', 'edad': 51, 'soltero': False, 'hobbies': ['senderismo', 'fotografía', 'ajedrez'], 'email': 'lucía67@correo.com', 'puntos': 328},
    {'nombre': 'Tomás', 'edad': 47, 'soltero': False, 'hobbies': [], 'email': 'tomás68@correo.com', 'puntos': 991},
    {'nombre': 'Valentina', 'edad': 63, 'soltero': False, 'hobbies': ['fotografía'], 'email': 'valentina69@mail.org', 'puntos': 694},
    {'nombre': 'Carlos', 'edad': 48, 'soltero': True, 'hobbies': [], 'email': 'carlos70@correo.com', 'puntos': 456},
    {'nombre': 'Lucía', 'edad': 22, 'soltero': False, 'hobbies': ['natación'], 'email': 'lucía71@correo.com', 'puntos': 486},
    {'nombre': 'Sofía', 'edad': 41, 'soltero': False, 'hobbies': ['senderismo'], 'email': 'sofía72@example.com', 'puntos': 887},
    {'nombre': 'Pedro', 'edad': 61, 'soltero': True, 'hobbies': ['lectura', 'pintura', 'natación'], 'email': 'pedro73@example.com', 'puntos': 278},
    {'nombre': 'Valentina', 'edad': 30, 'soltero': False, 'hobbies': ['natación', 'ciclismo'], 'email': 'valentina74@mail.org', 'puntos': 714},
    {'nombre': 'Pedro', 'edad': 28, 'soltero': True, 'hobbies': ['lectura'], 'email': 'pedro75@example.com', 'puntos': 624},
    {'nombre': 'Tomás', 'edad': 39, 'soltero': False, 'hobbies': [], 'email': 'tomás76@example.com', 'puntos': 618},
    {'nombre': 'Marta', 'edad': 43, 'soltero': True, 'hobbies': [], 'email': 'marta77@mail.org', 'puntos': 585},
    {'nombre': 'Valentina', 'edad': 34, 'soltero': False, 'hobbies': ['lectura', 'videojuegos'], 'email': 'valentina78@correo.com', 'puntos': 200},
    {'nombre': 'Pedro', 'edad': 63, 'soltero': False, 'hobbies': ['fotografía'], 'email': None, 'puntos': 622},
    {'nombre': 'Marta', 'edad': 63, 'soltero': False, 'hobbies': [], 'email': 'marta80@example.com', 'puntos': 878},
    {'nombre': 'Diego', 'edad': 58, 'soltero': False, 'hobbies': ['videojuegos', 'senderismo', 'ajedrez'], 'email': None, 'puntos': 551},
    {'nombre': 'Diego', 'edad': 35, 'soltero': True, 'hobbies': ['ajedrez', 'pintura', 'ciclismo'], 'email': None, 'puntos': 355},
    {'nombre': 'Lucía', 'edad': 41, 'soltero': True, 'hobbies': [], 'email': 'lucía83@correo.com', 'puntos': 230},
    {'nombre': 'Carlos', 'edad': 30, 'soltero': True, 'hobbies': ['pintura', 'ajedrez', 'natación'], 'email': 'carlos84@example.com', 'puntos': 544},
    {'nombre': 'Valentina', 'edad': 55, 'soltero': True, 'hobbies': ['pintura', 'lectura', 'senderismo'], 'email': None, 'puntos': 620},
    {'nombre': 'Ana', 'edad': 35, 'soltero': False, 'hobbies': ['fotografía', 'lectura', 'pintura'], 'email': 'ana86@mail.org', 'puntos': 268},
    {'nombre': 'Carlos', 'edad': 39, 'soltero': False, 'hobbies': [], 'email': None, 'puntos': 575},
    {'nombre': 'Pedro', 'edad': 65, 'soltero': False, 'hobbies': ['videojuegos', 'ajedrez', 'pintura'], 'email': 'pedro88@mail.org', 'puntos': 268},
    {'nombre': 'Carlos', 'edad': 21, 'soltero': False, 'hobbies': ['lectura'], 'email': 'carlos89@correo.com', 'puntos': 583},
    {'nombre': 'Lucía', 'edad': 57, 'soltero': True, 'hobbies': ['pintura'], 'email': 'lucía90@example.com', 'puntos': 624},
    {'nombre': 'Marta', 'edad': 60, 'soltero': True, 'hobbies': [], 'email': 'marta91@mail.org', 'puntos': 136},
    {'nombre': 'Marta', 'edad': 39, 'soltero': True, 'hobbies': ['ajedrez', 'fotografía'], 'email': 'marta92@correo.com', 'puntos': 274},
    {'nombre': 'Carlos', 'edad': 44, 'soltero': False, 'hobbies': ['ajedrez', 'videojuegos', 'senderismo'], 'email': None, 'puntos': 477},
    {'nombre': 'Carlos', 'edad': 29, 'soltero': True, 'hobbies': ['natación', 'lectura', 'fotografía'], 'email': None, 'puntos': 973},
    {'nombre': 'Luis', 'edad': 28, 'soltero': False, 'hobbies': ['videojuegos', 'senderismo', 'fotografía'], 'email': 'luis95@mail.org', 'puntos': 490},
    {'nombre': 'Carlos', 'edad': 42, 'soltero': True, 'hobbies': ['natación'], 'email': 'carlos96@correo.com', 'puntos': 329},
    {'nombre': 'Pedro', 'edad': 42, 'soltero': False, 'hobbies': ['ciclismo', 'natación', 'senderismo'], 'email': 'pedro97@example.com', 'puntos': 357},
    {'nombre': 'Carlos', 'edad': 36, 'soltero': True, 'hobbies': [], 'email': 'carlos98@correo.com', 'puntos': 860},
    {'nombre': 'Luis', 'edad': 27, 'soltero': True, 'hobbies': ['lectura'], 'email': None, 'puntos': 779},
]
